require recipes-core/images/ebaz4205-image-minimal.bb

SUMMARY = "EBAZ4205 image producing UBI/UBIFS artefacts for NAND."
DESCRIPTION = "\
Same rootfs as ebaz4205-image-minimal, but also generates .ubifs and \
.ubi images sized for the on-board 128 MiB Winbond W29N01HV (2048 B \
page, 128 KiB erase block). Use together with scripts/flash-nand.sh on \
a running (SD-booted) system to program the internal NAND.\
"

# UBIFS / UBI parameters for W29N01HV (SLC, 128 KiB erase, 2048 B page,
# LEB = 128 KiB - 2 * 2048 = 124 KiB = 0x1F000).
MKUBIFS_ARGS = "-m 2048 -e 126976 -c 820 -F"
UBINIZE_ARGS = "-m 2048 -p 128KiB -s 2048"

# Volume name matches what the target mounts as rootfs.
UBI_VOLNAME = "rootfs"

# Add the NAND fstypes on top of what the minimal image already produces
# (so the SD .wic is still generated by the same bitbake invocation).
IMAGE_FSTYPES += "ubi ubifs"

# Flashing helper + mtd-utils on target so `flash-nand` Just Works after
# SD boot.
IMAGE_INSTALL += " \
    nand-flash-tools \
    mtd-utils \
    mtd-utils-ubifs \
    "
